### ISSUE TITLE
'Panes' stuck at the top of the page

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/quest-js#3]
I've only seen the Inventory actually displayed, but it stays up top.  After two turns worth of scrolling down, it's gone.

It should be under the text input field, I think.

This should be an easy fix, using JS to set the CSS.

**Comment by tass23** [comment]
This is the CSS I am using and it sticks the Panes to the right side of the browser window:

`div#gamePanes
{
    background: white;
	width: fit-content;
	position: fixed;
	right: 0;
	top: 16px;
}`

position: fixed; is really all that is needed.

**Comment by KVonGit** [comment]
Fixed in the last update.
