### ISSUE TITLE
No instructions on how to use the tool

### ISSUE THREAD

**Issue by kinnzo** [KVonGit/quest-js#5]
I believe some information regarding how to use the tool to convert a quest game into js would be helpful to try and experiment with.

**Comment by KVonGit** [comment]
Hello.

1\. You load your source file (a .quest file).

2\. You select a destination directory.

3\. You cross your fingers and click 'Compile'.

---
There is a 95% chance you will have problems.  This is a 100% chance if you plan to make your game playable online.

See the issues and the wiki for known issues.  (I find a new problem at least once a day.  I fix some, but the ones listed have stumped me.)

---
Alex Warren abandoned this for a reason, but I've just now admitted this to myself.

I will be deleting this fork soon, so, if you want this "almost works" version, the time to download the files is definitely now.

---
I apologize.  I assume you were just as excited about this as I was when I found it, but there are major problems which appear to be insurmountable.

One of the forum members is working on something similar to this, except it will work (and it will run on Linux, Mac, or Windows).  Once it becomes public, I'll make sure you get the link.

---
Have a nice day!
